[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx esbuild game-server/index.ts --bundle --platform=node --packages=external --outdir=game-server/dist", "npx next build", "npx esbuild server.ts --bundle --platform=node --packages=external --outdir=dist"]

[start]
cmd = "node game-server/dist/index.js"
